DROP TABLE IF EXISTS `MEMBER`;

CREATE TABLE `MEMBER` (
	`MEM_NO`	NUMBER	NOT NULL	COMMENT '회원번호',
	`MEM_ID`	VARCHAR2(16)	NOT NULL	COMMENT '회원아이디',
	`MEM_PWD`	VARCHAR2(16)	NOT NULL	COMMENT '회원비밀번호',
	`MEM_NAME`	VARCHAR2(10)	NOT NULL	COMMENT '회원명',
	`ADDRESS`	VARCHAR2(100)	NOT NULL	COMMENT '회원주소',
	`ADDRESS_DETAIL`	VARCHAR2(50)	NOT NULL	COMMENT '상세주소',
	`PHONE`	VARCHAR2(18)	NOT NULL	COMMENT '회원전화번호',
	`EMAIL`	VARCHAR2(50)	NOT NULL	COMMENT '회원이메일',
	`BIRTH_DATE`	DATE	NOT NULL	COMMENT '회원생년월일',
	`GENDER`	CHAR(2)	NOT NULL	COMMENT '회원성별',
	`GRADE`	VARCHAR2(10)	NOT NULL	DEFAULT '작은산(미정)'	COMMENT '회원등급',
	`ENROLL_DATE`	DATE	NOT NULL	DEFAULT SYSDATE	COMMENT '회원가입일',
	`STOP_YN`	CHAR(2)	NOT NULL	DEFAULT 'N'	COMMENT '회원정지여부',
	`STOP_DATE`	DATE	NULL	COMMENT '회원정지날짜',
	`DROP_YN`	CHAR(2)	NOT NULL	DEFAULT 'N'	COMMENT '회원탈퇴여부',
	`DROP_DATE`	DATE	NULL	DEFAULT SYSDATE	COMMENT '회원탈퇴일',
	`REP_COUNT`	NUMBER	NULL	DEFAULT 0	COMMENT '신고당한횟수'
);

DROP TABLE IF EXISTS `BOARD`;

CREATE TABLE `BOARD` (
	`BOARD_NO`	VARCHAR(255)	NOT NULL,
	`MEM_NO`	NUMBER	NOT NULL	COMMENT '회원번호',
	`BOARD_NAME`	VARCHAR2(30)	NOT NULL	COMMENT '자유게시판, 피드게시판, 리뷰게시판, Q&A, 동행게시판',
	`BOARD_HT`	VARCHAR2(20)	NULL	COMMENT '말머리',
	`BOARD_TITLE`	VARCHAR2(50)	NOT NULL	COMMENT '글제목',
	`BOARD_CONTENT`	VARCHAR2(1000)	NULL	COMMENT '글내용',
	`BOARD_FILE`	VARCHAR2(500)	NULL	COMMENT '첨부파일의 URL',
	`BOARD_THUMBNAIL`	VARCHAR2(500)	NULL	COMMENT '썸네일의 URL',
	`BOARD_CREATE_DATE`	DATE	NOT NULL	DEFAULT SYSDATE	COMMENT '작성일',
	`BOARD_VIEW_COUNT`	NUMBER	NOT NULL	COMMENT '조회수',
	`BOARD_REPORT_STATUS`	VARCHAR2(5)	NOT NULL	COMMENT '신고여부',
	`BOARD_DELETE_STATUS`	VARCHAR(5)	NOT NULL	COMMENT '삭제여부',
	`METERIAL`	VARCHAR2(50)	NULL	COMMENT '준비물',
	`KEYWORD`	VARCHAR2(40)	NULL	COMMENT '키워드(해시태그)',
	`DP_DATE`	DATE	NULL	COMMENT '출발날짜',
	`MEMBER_COUNT`	NUMBER	NULL	COMMENT '모집인원',
	`BOARD_ANSWER_YN`	CHAR(2)	NULL	DEFAULT 'N'	COMMENT '답변대기 - 'N' / 답변등록 - 'Y'',
	`LIKE_COUNT`	NUMBER	NOT NULL	DEFAULT 0
);

DROP TABLE IF EXISTS `REPORT`;

CREATE TABLE `REPORT` (
	`REP_NO`	NUMBER	NOT NULL	COMMENT '신고번호',
	`REP_REASON`	VARCHAR2(30)	NOT NULL	COMMENT '신고사유(카테고리)',
	`REP_CONTENT`	VARCHAR2(200)	NOT NULL	COMMENT '신고글 내용',
	`REP_DATE`	DATE	NOT NULL	DEFAULT SYSDATE	COMMENT '신고 날짜',
	`REP_YN`	CHAR(2)	NOT NULL	DEFAULT 'N'	COMMENT '처리 완료 : 'Y' / 처리중 : 'N'',
	`REP_USER`	NUMBER	NOT NULL	COMMENT '회원번호(신고한 유저)',
	`BOARD_NO`	NUMBER	NULL	COMMENT '신고된 글 번호',
	`REPLY_NO`	NUMBER	NULL	COMMENT '신고된 댓글 번호',
	`Field`	NUMBER	NULL	COMMENT '신고된 유저'
);

DROP TABLE IF EXISTS `MESSAGE`;

CREATE TABLE `MESSAGE` (
	`MSG_NO`	NUMBER	NOT NULL	COMMENT '쪽지번호',
	`MSG_CONTENT`	VARCHAR2(300)	NULL	COMMENT '쪽지내용',
	`MSG_SEND_DATE`	DATE	NOT NULL	DEFAULT SYSDATE	COMMENT '보낸 날짜',
	`RECIPIENT`	VARCHAR2(10)	NULL	COMMENT '받는 사람',
	`MSG_CHECK_YN`	CHAR(2)	NOT NULL	DEFAULT 'N'	COMMENT '확인여부',
	`MEM_NO`	NUMBER	NOT NULL	COMMENT '회원번호'
);

DROP TABLE IF EXISTS `REPLY`;

CREATE TABLE `REPLY` (
	`REPLY_NO`	NUMBER	NOT NULL	COMMENT '댓글번호',
	`MEM_NO`	NUMBER	NOT NULL	COMMENT '작성자회원번호',
	`BOARD_NO`	VARCHAR(255)	NOT NULL	COMMENT '게시글 글번호',
	`REPLY_CONTENT`	VARCHAR2(400)	NOT NULL	COMMENT '댓글내용',
	`REPLY_CREATE_DATE`	DATE	NOT NULL	DEFAULT SYSDATE	COMMENT '댓글작성일',
	`REPLY_REPORT_YN`	CHAR(2)	NULL	DEFAULT 'N'	COMMENT '신고:'Y'',
	`REPLY_DELETE_YN`	CHAR(2)	NULL	DEFAULT 'N'	COMMENT '삭제:'Y''
);

DROP TABLE IF EXISTS `Q&A`;

CREATE TABLE `Q&A` (
	`QUESTION_NO`	NUMBER	NOT NULL	COMMENT '문의글 식별 번호',
	`QUESTION_TITLE`	VARCHAR2(30)	NOT NULL	COMMENT '문의글 제목',
	`QUESTION_CONTENT`	VARCHAR2(200)	NULL	COMMENT '문의 내용',
	`QUESTION_CREATE_DATE`	DATE	NULL	DEFAULT SYSDATE	COMMENT '문의글 등록일',
	`QUESTION_YN`	CHAR(2)	NOT NULL	DEFAULT 'N'	COMMENT '처리 완료 : 'Y' / 처리중 : 'N'',
	`MEM_NO`	NUMBER	NOT NULL	COMMENT '회원번호',
	`ANSWER_CONTENT`	VARCHAR2(1000)	NOT NULL	COMMENT '문의글 답변 내용'
);

DROP TABLE IF EXISTS `CHAT`;

CREATE TABLE `CHAT` (
	`CHAT_NO`	NUMBER	NOT NULL	COMMENT '대화방번호',
	`CHAT_NAME`	VARCHAR2(50)	NOT NULL	COMMENT '대화방 이름',
	`CHAT_CONTENT`	VARCHAR2(300)	NULL	COMMENT '채팅 내용',
	`CHAT_CREATE_DATE`	DATE	NULL	DEFAULT SYSDATE	COMMENT '채팅 작성일',
	`MEM_NO`	NUMBER	NOT NULL	COMMENT '회원 번호',
	`BOARD_NO`	NUMBER	NOT NULL	COMMENT '글 번호'
);

DROP TABLE IF EXISTS `LIKE`;

CREATE TABLE `LIKE` (
	`USER_NO`	NUMBER	NOT NULL	COMMENT '좋아요 누른 회원 번호',
	`BOARD_NO`	NUMBER	NOT NULL	COMMENT '좋아요 누른 게시판 글 번호',
	`LIKE_YN`	VARCHAR(255)	NOT NULL	DEFAULT 'N'	COMMENT '좋아요 누르면 Y 아니면 N'
);

DROP TABLE IF EXISTS `INFOMATION`;

CREATE TABLE `INFOMATION` (
	`INFO_NO`	NUMBER	NOT NULL	COMMENT '정보글번호',
	`INFO_TYPE`	VARCHAR2(20)	NOT NULL	COMMENT '지역별 산, 계절별산, 초보자 길잡이',
	`SEASON`	VARCHAR2(10)	NULL	COMMENT '봄, 여름, 가을, 겨울',
	`INFO_TITLE`	VARCHAR2(50)	NOT NULL	COMMENT '정보글 제목',
	`INFO_CONTENT`	VARCHAR2(1000)	NOT NULL	COMMENT '내용',
	`INFO_MEDIA`	VARCHAR2(500)	NULL	COMMENT '사진, 동영상 URL 저장 컬럼',
	`INFO_CREATE_DATE`	DATE	NULL	DEFAULT SYSDATE	COMMENT '작성일',
	`INFO_COUNT`	NUMBER	NOT NULL	DEFAULT 0	COMMENT 'SEQUENCE를 통해 측정',
	`INFO_WRITER`	VARCHAR2(20)	NOT NULL	COMMENT '관리자의 아이디 또는 번호',
	`INFO_DELETE_YN`	CHAR(2)	NULL	DEFAULT 'N'	COMMENT '삭제-'Y' / 유지-'N'',
	`MEM_NO`	NUMBER	NOT NULL,
	`TYPE`	VARCHAR(255)	NOT NULL	DEFAULT 'INFORMATION',
	`local`	VARCHAR(255)	NOT NULL	COMMENT '서울/인천',
	`TURNAROUND`	NUMBER	NOT NULL,
	`COURSE`	VARCHAR2(500)	NOT NULL,
	`TRAFFIC`	VARCHAR2(500)	NOT NULL
);

DROP TABLE IF EXISTS `NOTICE`;

CREATE TABLE `NOTICE` (
	`NOTICE_NO`	NUMBER	NOT NULL	COMMENT '공지글번호',
	`NOTICE_TITLE`	VARCHAR2(50)	NOT NULL	COMMENT '글제목',
	`NOTICE_CONTENT`	VARCHAR2(1000)	NULL	COMMENT '글내용',
	`NOTICE_COUNT`	NUMBER	NULL	COMMENT '조회수',
	`NOTICE_BOARD_NAME`	VARCHAR2(20)	NOT NULL	COMMENT 'FK로 게시판이랑 연결쓰',
	`NOTICE_CREATE_DATE`	DATE	NOT NULL	DEFAULT SYSDATE	COMMENT '작성일',
	`MEM_NO`	NUMBER	NOT NULL	COMMENT '관리자',
	`TYPE`	VARCHAR(255)	NOT NULL	DEFAULT NOTICE,
	`DELETE_YN`	CHAR(2)	NOT NULL	COMMENT '삭제 : Y / 미삭제 : N'
);

DROP TABLE IF EXISTS `ACEEPT`;

CREATE TABLE `ACEEPT` (
	`CHAT_NO`	NUMBER	NOT NULL	COMMENT '대화방번호',
	`USER_NO`	NUMBER	NOT NULL	COMMENT '수락된 회원번호',
	`CHAT_ACCEPT_YN`	CHAR(2)	NOT NULL	DEFAULT 'N'	COMMENT '수락-'Y' / 거절-'N''
);

DROP TABLE IF EXISTS `PARTICIPANT`;

CREATE TABLE `PARTICIPANT` (
	`CHAT_NO`	NUMBER	NOT NULL	COMMENT '대화방번호',
	`MEM_NO`	NUMBER	NOT NULL	COMMENT '회원번호',
	`APPLY_NO`	NUMBER	NULL	COMMENT '동행신청자수',
	`KEYWORD`	VARCHA2(40)	NULL	COMMENT '신청한사람의키워드'
);

DROP TABLE IF EXISTS `Untitled`;

CREATE TABLE `Untitled` (
	`BOARD_NO`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL,
	`Field5`	VARCHAR(255)	NULL,
	`Field6`	VARCHAR(255)	NULL
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
	`MEM_NO`
);

ALTER TABLE `BOARD` ADD CONSTRAINT `PK_BOARD` PRIMARY KEY (
	`BOARD_NO`
);

ALTER TABLE `REPORT` ADD CONSTRAINT `PK_REPORT` PRIMARY KEY (
	`REP_NO`
);

ALTER TABLE `MESSAGE` ADD CONSTRAINT `PK_MESSAGE` PRIMARY KEY (
	`MSG_NO`
);

ALTER TABLE `REPLY` ADD CONSTRAINT `PK_REPLY` PRIMARY KEY (
	`REPLY_NO`
);

ALTER TABLE `Q&A` ADD CONSTRAINT `PK_Q&A` PRIMARY KEY (
	`QUESTION_NO`
);

ALTER TABLE `CHAT` ADD CONSTRAINT `PK_CHAT` PRIMARY KEY (
	`CHAT_NO`
);

ALTER TABLE `LIKE` ADD CONSTRAINT `PK_LIKE` PRIMARY KEY (
	`USER_NO`,
	`BOARD_NO`
);

ALTER TABLE `INFOMATION` ADD CONSTRAINT `PK_INFOMATION` PRIMARY KEY (
	`INFO_NO`
);

ALTER TABLE `NOTICE` ADD CONSTRAINT `PK_NOTICE` PRIMARY KEY (
	`NOTICE_NO`
);

ALTER TABLE `ACEEPT` ADD CONSTRAINT `PK_ACEEPT` PRIMARY KEY (
	`CHAT_NO`,
	`USER_NO`
);

ALTER TABLE `LIKE` ADD CONSTRAINT `FK_MEMBER_TO_LIKE_1` FOREIGN KEY (
	`USER_NO`
)
REFERENCES `MEMBER` (
	`MEM_NO`
);

ALTER TABLE `LIKE` ADD CONSTRAINT `FK_BOARD_TO_LIKE_1` FOREIGN KEY (
	`BOARD_NO`
)
REFERENCES `BOARD` (
	`BOARD_NO`
);

ALTER TABLE `ACEEPT` ADD CONSTRAINT `FK_CHAT_TO_ACEEPT_1` FOREIGN KEY (
	`CHAT_NO`
)
REFERENCES `CHAT` (
	`CHAT_NO`
);

ALTER TABLE `ACEEPT` ADD CONSTRAINT `FK_MEMBER_TO_ACEEPT_1` FOREIGN KEY (
	`USER_NO`
)
REFERENCES `MEMBER` (
	`MEM_NO`
);

